from collections.abc import Iterable
from pathlib import Path, PurePosixPath

import pytest

from codeindex.repository.discovery import (
    discover_files,
    summarize_discovery,
)
from codeindex.repository.models import (
    DiscoveredFile,
    Repository,
    SkipReason,
    SkippedFile,
    TrackedFile,
)


def tracked(
    path: str,
    *,
    mode: str = "100644",
    stage: int = 0,
) -> TrackedFile:
    return TrackedFile(PurePosixPath(path), mode, stage)


def discover(
    root: Path,
    entries: Iterable[TrackedFile],
    **kwargs: object,
) -> list[DiscoveredFile | SkippedFile]:
    return list(
        discover_files(
            Repository(root=root),
            tracked_files_lookup=lambda repository_root: entries,
            **kwargs,
        )
    )


def write(root: Path, relative_path: str, content: bytes) -> Path:
    path = root / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return path


def test_accepts_current_utf8_working_tree_content(tmp_path: Path) -> None:
    write(tmp_path, "src/app.py", b"\xef\xbb\xbfprint('modified')\n")

    decisions = discover(tmp_path, [tracked("src/app.py")])

    assert decisions == [
        DiscoveredFile(
            relative_path=PurePosixPath("src/app.py"),
            text="print('modified')\n",
            size_bytes=21,
        )
    ]


@pytest.mark.parametrize(
    ("entry", "reason"),
    [
        (tracked("deleted.py"), SkipReason.DELETED),
        (tracked("link.py", mode="120000"), SkipReason.SYMLINK),
        (tracked("module", mode="160000"), SkipReason.SUBMODULE),
        (tracked("conflict.py", stage=2), SkipReason.UNMERGED),
        (tracked("special.py", mode="100600"), SkipReason.UNSUPPORTED_GIT_ENTRY),
        (tracked("../outside.py"), SkipReason.UNSAFE_PATH),
    ],
)
def test_classifies_git_entry_and_path_failures(
    tmp_path: Path,
    entry: TrackedFile,
    reason: SkipReason,
) -> None:
    decisions = discover(tmp_path, [entry])

    assert decisions == [SkippedFile(entry.relative_path, reason)]


def test_skips_working_tree_symlink_and_symlinked_parent(tmp_path: Path) -> None:
    target = write(tmp_path, "target.py", b"print('target')\n")
    (tmp_path / "link.py").symlink_to(target)
    outside = tmp_path / "outside"
    outside.mkdir()
    write(outside, "nested.py", b"print('outside')\n")
    (tmp_path / "linked-directory").symlink_to(outside, target_is_directory=True)

    decisions = discover(
        tmp_path,
        [tracked("link.py"), tracked("linked-directory/nested.py")],
    )

    assert decisions == [
        SkippedFile(PurePosixPath("link.py"), SkipReason.SYMLINK),
        SkippedFile(
            PurePosixPath("linked-directory/nested.py"),
            SkipReason.SYMLINK,
        ),
    ]


@pytest.mark.parametrize(
    ("relative_path", "reason"),
    [
        (".env", SkipReason.SECRET),
        (".env.production", SkipReason.SECRET),
        ("keys/server.pem", SkipReason.SECRET),
        ("node_modules/package/index.js", SkipReason.DEPENDENCY),
        ("vendor/library.py", SkipReason.DEPENDENCY),
        ("dist/app.js", SkipReason.GENERATED),
        ("src/app.min.js", SkipReason.GENERATED),
        ("uv.lock", SkipReason.GENERATED),
    ],
)
def test_applies_path_exclusion_policy(
    tmp_path: Path,
    relative_path: str,
    reason: SkipReason,
) -> None:
    write(tmp_path, relative_path, b"safe-looking text\n")

    decisions = discover(tmp_path, [tracked(relative_path)])

    assert decisions == [
        SkippedFile(PurePosixPath(relative_path), reason)
    ]


@pytest.mark.parametrize(
    "relative_path",
    [".env.example", ".env.sample", ".env.template"],
)
def test_accepts_safe_environment_templates(
    tmp_path: Path,
    relative_path: str,
) -> None:
    write(tmp_path, relative_path, b"SETTING=example\n")

    decisions = discover(tmp_path, [tracked(relative_path)])

    assert isinstance(decisions[0], DiscoveredFile)


def test_secret_reason_precedes_dependency_reason(tmp_path: Path) -> None:
    write(tmp_path, "vendor/.env", b"TOKEN=secret\n")

    decisions = discover(tmp_path, [tracked("vendor/.env")])

    assert decisions == [
        SkippedFile(PurePosixPath("vendor/.env"), SkipReason.SECRET)
    ]


@pytest.mark.parametrize(
    ("content", "reason"),
    [
        (b"", SkipReason.EMPTY),
        (b" \n\t", SkipReason.EMPTY),
        (b"\0binary", SkipReason.BINARY),
        (b"caf\xe9", SkipReason.UNSUPPORTED_ENCODING),
        (b"# @generated\nprint('generated')\n", SkipReason.GENERATED),
        (
            b"# Code generated by a tool. DO NOT EDIT.\nprint('generated')\n",
            SkipReason.GENERATED,
        ),
    ],
)
def test_applies_content_exclusion_policy(
    tmp_path: Path,
    content: bytes,
    reason: SkipReason,
) -> None:
    write(tmp_path, "src/app.py", content)

    decisions = discover(tmp_path, [tracked("src/app.py")])

    assert decisions == [
        SkippedFile(PurePosixPath("src/app.py"), reason)
    ]


def test_enforces_inclusive_file_size_limit(tmp_path: Path) -> None:
    write(tmp_path, "accepted.txt", b"a" * 10)
    write(tmp_path, "oversized.txt", b"a" * 11)

    decisions = discover(
        tmp_path,
        [tracked("accepted.txt"), tracked("oversized.txt")],
        max_file_bytes=10,
    )

    assert decisions == [
        DiscoveredFile(PurePosixPath("accepted.txt"), "a" * 10, 10),
        SkippedFile(PurePosixPath("oversized.txt"), SkipReason.OVERSIZED),
    ]


@pytest.mark.parametrize(
    ("relative_path", "content"),
    [
        ("src/app.py", b"print('hello')\n"),
        (
            "app/services/report_service.rb",
            b"@generated_report = generated_report\n",
        ),
        (
            "app/views/reports/show.html.erb",
            b"<%= render @generated_report %>\n",
        ),
        ("README", b"Project documentation\n"),
        ("Dockerfile.dev", b"FROM python:3.12\n"),
        ("bin/codeindex", b"#!/bin/sh\nexec python -m codeindex\n"),
    ],
)
def test_accepts_curated_file_types(
    tmp_path: Path,
    relative_path: str,
    content: bytes,
) -> None:
    write(tmp_path, relative_path, content)

    decisions = discover(tmp_path, [tracked(relative_path)])

    assert isinstance(decisions[0], DiscoveredFile)


@pytest.mark.parametrize(
    "relative_path",
    [
        "fixtures/events.data",
        "assets/icon.svg",
        "config/schema.xml",
    ],
)
def test_skips_unsupported_text_type(
    tmp_path: Path,
    relative_path: str,
) -> None:
    write(tmp_path, relative_path, b"text content\n")

    decisions = discover(tmp_path, [tracked(relative_path)])

    assert decisions == [
        SkippedFile(
            PurePosixPath(relative_path),
            SkipReason.UNSUPPORTED_TYPE,
        )
    ]


def test_reports_read_failure_as_unreadable(tmp_path: Path) -> None:
    write(tmp_path, "src/app.py", b"print('hello')\n")

    def fail_read(path: Path, byte_limit: int) -> bytes:
        raise PermissionError

    decisions = discover(
        tmp_path,
        [tracked("src/app.py")],
        file_reader=fail_read,
    )

    assert decisions == [
        SkippedFile(PurePosixPath("src/app.py"), SkipReason.UNREADABLE)
    ]


def test_discovery_reads_only_the_current_item(tmp_path: Path) -> None:
    write(tmp_path, "first.py", b"first = True\n")
    write(tmp_path, "second.py", b"second = True\n")
    reads: list[str] = []

    def record_read(path: Path, byte_limit: int) -> bytes:
        reads.append(path.name)
        return path.read_bytes()

    decisions = discover_files(
        Repository(tmp_path),
        tracked_files_lookup=lambda root: [
            tracked("first.py"),
            tracked("second.py"),
        ],
        file_reader=record_read,
    )

    first = next(decisions)

    assert isinstance(first, DiscoveredFile)
    assert reads == ["first.py"]


def test_summary_groups_reasons_deterministically() -> None:
    decisions = [
        SkippedFile(PurePosixPath("z.py"), SkipReason.GENERATED),
        DiscoveredFile(PurePosixPath("a.py"), "a = 1\n", 6),
        SkippedFile(PurePosixPath("b.py"), SkipReason.BINARY),
        SkippedFile(PurePosixPath("c.py"), SkipReason.BINARY),
    ]

    summary = summarize_discovery(decisions)

    assert summary.candidate_count == 4
    assert summary.accepted_count == 1
    assert summary.skipped_count == 3
    assert summary.skipped_by_reason == (
        (SkipReason.BINARY, 2),
        (SkipReason.GENERATED, 1),
    )


def test_handles_ten_thousand_candidates_without_reading_content(
    tmp_path: Path,
) -> None:
    entries = [tracked(f"missing/{index:05}.py") for index in range(10_000)]

    summary = summarize_discovery(
        discover_files(
            Repository(tmp_path),
            tracked_files_lookup=lambda root: entries,
        )
    )

    assert summary.candidate_count == 10_000
    assert summary.accepted_count == 0
    assert summary.skipped_by_reason == ((SkipReason.DELETED, 10_000),)
